# -*- coding: utf-8 -*-
"""PTS MP1 XI Mirza Rafa.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13gGDb4nFOFRQcU1GpPLUH-dUGXr4t9F0
"""

from google.colab import drive
drive.mount('/content/drive')

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import tensorflow as tf

from tensorflow import keras
from tensorflow.keras import layers

data_train_path = '/content/drive/MyDrive/PTS MP1_XI Mirza Rafa Raidhitya/5 best football players/Football players/train'
data_test_path = '/content/drive/MyDrive/PTS MP1_XI Mirza Rafa Raidhitya/5 best football players/Football players/test'
data_vel_path = '/content/drive/MyDrive/PTS MP1_XI Mirza Rafa Raidhitya/5 best football players/Football players/valid'

img_width = 180
img_height = 180

data_train = tf.keras.utils.image_dataset_from_directory(
    data_train_path,
    image_size=(img_width, img_height),
    batch_size=32,
    validation_split=False)

data_cat = data_train.class_names

data_val = tf.keras.utils.image_dataset_from_directory(
    data_train_val,
    image_size=(img_width, img_height),
    batch_size=32,
    validation_split=False)

data_test = tf.keras.utils.image_dataset_from_directory(
    data_test_path,
    image_size=(img_width, img_height),
    shuffle=False,
    batch_size=32,
    validation_split=False)

plt.figure(figsize=(10, 10))
for image, labels in data_train.take(1):
    for i in range(9):
        plt.subplot(3, 3, i + 1)
        plt.imshow(image[i].numpy().astype("uint8"))
        plt.title(data_cat[labels[i]])
        plt.axis("off")

from tensorflow.keras.models import Sequential

model = Sequential([
    layers.Rescaling(1./255, input_shape=(img_height, img_width, 3)),
    layers.Conv2D(16, 3, padding='same', activation='relu'),
    layers.MaxPooling2D(),
    layers.Conv2D(32, 3, padding='same', activation='relu'),
    layers.MaxPooling2D(),
    layers.Conv2D(64, 3, padding='same', activation='relu'),
    layers.MaxPooling2D(),
    layers.Flatten(),
    layers.Dropout(0.2),
    layers.Dense(128),
    layers.Dense(len(data_cat))
])

model.compile(optimizer='adam',
              loss=tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True),
              metrics=['accuracy'])

apochs_size = 25
model.fit(data_train, validation_data=data_val, epochs=apochs_size,)

epochs_range = range(apochs_size)
plt.figure(figsize=(8, 8))
plt.subplot(1, 2, 1)
plt.plot(epochs_range, model.history.history['accuracy'], label='Training Accuracy')
plt.plot(epochs_range, model.history.history['val_accuracy'], label='Validation Accuracy')
plt.title('Accuracy')

plt.subplot(1, 2, 2)
plt.plot(epochs_range, model.history.history['accuracy'], label='Training Accuracy')
plt.plot(epochs_range, model.history.history['val_accuracy'], label='Validation Loss')
plt.title('Loss')

image = '/content/drive/MyDrive/PTS MP1_XI Mirza Rafa Raidhitya/5 best football players/Football players/test/Ronaldo/4.jpg'
image = tf.keras.utils.load_img(image, target_size=(img_height, img_width))
img_arr = tf.keras.utils.img_to_array(image)
img_arr = tf.expand_dims(img_arr, 0)

predict = model.predict(img_arr)

score = tf.nn.softmax(predict)

print('in this image Football Players is {} with accuracy of {:.2f}'.format(data_cat[np.argmax(score)], 100 * np.max(score)))

model.save('image_classify.keras')

